spring.application.name=my-own-blog

# DB Connection
# Letting Spring Boot Docker Compose handle MongoDB connection automatically

# Configuration for Live Reload
spring.devtools.restart.exclude=static/**,public/**,templates/**
spring.devtools.restart.additional-paths=src/main/resources/templates,src/main/resources/static
spring.devtools.livereload.enabled=true
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=file:src/main/resources/templates/
spring.web.resources.static-locations=file:src/main/resources/static/
spring.main.allow-bean-definition-overriding=true

globalPreferencesId=GlobalPreferencesId